// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuiTk87_9ZKRFYlgg6XBStl3iLOps0Pik',
    appId: '1:549431673583:web:c982690588d28cae4b911a',
    messagingSenderId: '549431673583',
    projectId: 'codelabs-74e2f',
    authDomain: 'codelabs-74e2f.firebaseapp.com',
    storageBucket: 'codelabs-74e2f.appspot.com',
    measurementId: 'G-N2XLE5D1Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzvInQazNiJoo-jmCfe5654iRw2kIMz4',
    appId: '1:549431673583:android:8d458262a45691ec4b911a',
    messagingSenderId: '549431673583',
    projectId: 'codelabs-74e2f',
    storageBucket: 'codelabs-74e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7q3iSueisxazv5cVq_vexZwelng-j0vk',
    appId: '1:549431673583:ios:fb94c39e8ee60e5a4b911a',
    messagingSenderId: '549431673583',
    projectId: 'codelabs-74e2f',
    storageBucket: 'codelabs-74e2f.appspot.com',
    iosBundleId: 'com.example.flutterCodelabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7q3iSueisxazv5cVq_vexZwelng-j0vk',
    appId: '1:549431673583:ios:e9c76381b150046d4b911a',
    messagingSenderId: '549431673583',
    projectId: 'codelabs-74e2f',
    storageBucket: 'codelabs-74e2f.appspot.com',
    iosBundleId: 'com.example.flutterCodelabs.RunnerTests',
  );
}
